package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"ServerBTI/graph/assistant"
	"ServerBTI/graph/model"
	"ServerBTI/internal/models"
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.User, error) {
	user_DataBase := &models.User{
		Login:    input.Login,
		Username: input.Username,
		Password: input.Password,
		Email:    input.Email,
		Birthday: input.Birthday,
	}
	user_graphql := &model.User{
		ID:       fmt.Sprintf("%d", user_DataBase.ID),
		Username: user_DataBase.Username,
		Email:    user_DataBase.Email,
		Login:    user_DataBase.Login,
	}

	if err := r.DB.Create(user_DataBase).Error; err != nil {
		return user_graphql, err
	}
	return user_graphql, nil
}

// CreatePlanningProject is the resolver for the createPlanningProject field.
func (r *mutationResolver) CreatePlanningProject(ctx context.Context, input model.PlanningProjectInput) (*model.PlanningProject, error) {
	inputJSON, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("ошибка подготовки данных для анализа: %w", err)
	}
	aiAnalyze, err := assistant.AiAnalyze(string(inputJSON))
	if err != nil {
		return nil, err
	}

	if !aiAnalyze.IsValid {
		return nil, fmt.Errorf("проект не прошёл проверку. Решение: %s. Обоснование: %s",
			aiAnalyze.Decision, aiAnalyze.Justification)
	}
	db := r.DB

	project := models.PlanningProject{
		Status:            aiAnalyze.Decision,
		Address:           input.Plan.Address,
		Area:              fmt.Sprintf("%f", input.Plan.Area),
		Source:            input.Plan.Source,
		LayoutType:        input.Plan.LayoutType,
		FamilyProfile:     input.Plan.FamilyProfile,
		Goal:              input.Plan.Goal,
		Prompt:            input.Plan.Prompt,
		CeilingHeight:     fmt.Sprintf("%f", input.Plan.CeilingHeight),
		FloorDelta:        fmt.Sprintf("%f", input.Plan.FloorDelta),
		RecognitionStatus: input.Plan.RecognitionStatus,
	}

	if err := db.Create(&project).Error; err != nil {
		return nil, fmt.Errorf("ошибка сохранения проекта: %w", err)
	}

	// --- 4. Сохраняем комнаты ---
	for _, roomInput := range input.Geometry.Rooms {
		room := models.Room{
			ProjectID: project.ID,
			Name:      roomInput.Name,
			Height:    fmt.Sprintf("%f", roomInput.Height),
		}
		if err := db.Create(&room).Error; err != nil {
			return nil, err
		}

		for _, v := range roomInput.Vertices {
			vertex := models.RoomVertex{
				RoomID: room.ID,
				X:      fmt.Sprintf("%f", v.X),
				Y:      fmt.Sprintf("%f", v.Y),
			}
			if err := db.Create(&vertex).Error; err != nil {
				return nil, err
			}
		}
	}

	// --- 5. Сохраняем стены ---
	for _, wallInput := range input.Walls {
		wall := models.Wall{
			ProjectID:   project.ID,
			StartX:      fmt.Sprintf("%f", wallInput.Start.X),
			StartY:      fmt.Sprintf("%f", wallInput.Start.Y),
			EndX:        fmt.Sprintf("%f", wallInput.End.X),
			EndY:        fmt.Sprintf("%f", wallInput.End.Y),
			LoadBearing: wallInput.LoadBearing,
			Thickness:   fmt.Sprintf("%f", wallInput.Thickness),
		}
		if err := db.Create(&wall).Error; err != nil {
			return nil, err
		}
	}

	// --- 6. Сохраняем ограничения, если есть ---
	if input.Constraints != nil {
		constraints := models.Constraints{
			ProjectID:      project.ID,
			ForbiddenMoves: strings.Join(input.Constraints.ForbiddenMoves, ","),
			RegionRules:    strings.Join(input.Constraints.RegionRules, ","),
		}
		if err := db.Create(&constraints).Error; err != nil {
			return nil, err
		}
	}

	// --- 7. Возвращаем GraphQL модель ---
	return ConvertDbProjectToGraph(&project), nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	uid, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	var user_DataBase models.User

	if err := r.DB.First(&user_DataBase, uid).Error; err != nil {
		return nil, err
	}

	user_graphql := &model.User{
		Login:    user_DataBase.Login,
		Username: user_DataBase.Username,
		Email:    user_DataBase.Email,
	}

	return user_graphql, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) GetUserProjects(ctx context.Context, userId string) ([]*model.PlanningProject, error) {
	uid, err := strconv.ParseInt(userId, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	// Загружаем из базы
	var dbProjects []models.PlanningProject
	if err := r.DB.Where("user_id = ?", uid).Find(&dbProjects).Error; err != nil {
		return nil, err
	}

	// Конвертация в GraphQL модели
	gqlProjects := make([]*model.PlanningProject, 0, len(dbProjects))
	for _, p := range dbProjects {
		gqlProjects = append(gqlProjects, ConvertDbProjectToGraph(&p))
	}

	return gqlProjects, nil
}
*/
