package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"ServerBTI/graph/assistant"
	"ServerBTI/graph/model"
	"ServerBTI/internal/models"
	"context"
	"fmt"
	"strconv"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.User, error) {
	user_DataBase := &models.User{
		Login:    input.Login,
		Username: input.Username,
		Password: input.Password,
		Email:    input.Email,
	}
	user_graphql := &model.User{
		ID:       fmt.Sprintf("%d", user_DataBase.ID),
		Username: user_DataBase.Username,
		Email:    user_DataBase.Email,
		Login:    user_DataBase.Login,
	}

	if err := r.DB.Create(user_DataBase).Error; err != nil {
		return user_graphql, err
	}
	return user_graphql, nil
}

// AskBTIagent is the resolver for the askBTIagent field.
func (r *mutationResolver) AskBTIagent(ctx context.Context, input model.BtiAgent) (*string, error) {
	request, err := assistant.AskAgent(input.Prompt)

	if err != nil {
		return nil, err
	}
	return &request, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	uid, _ := strconv.Atoi(id)

	var user_DataBase models.User

	if err := r.DB.First(&user_DataBase, uid).Error; err != nil {
		return nil, err
	}

	user_graphql := &model.User{
		Login:    user_DataBase.Login,
		Username: user_DataBase.Username,
		Email:    user_DataBase.Email,
	}

	return user_graphql, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
