// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BtiAgent struct {
	ID     string `json:"id"`
	Prompt string `json:"prompt"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Login    string `json:"login"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Login    string `json:"login"`
	Username string `json:"username"`
}
